### ISSUE TITLE
How To:  To have two blog directories and an associated issue

### ISSUE THREAD

**Issue by linlennypinawa** [hugo-apero/hugo-apero#103]
I am doing an experiment.  I created two blog directories.  My header in `config.yaml` looks like this:

```
  header:
    - name: About
      title: About Blogophonic
      url: /about/
      weight: 1
    - name: blog_1
      title: Blog
      url: /blog/
      weight: 2
    - name: blog_2
      title: Blog
      url: /blog_2/
      weight: 3
```

The blog "blog_1" looks fine, but the blog "blog_2" is problematic.  The sidebar disappears.  The yaml of index.md under the "blog_2" directory is as follows:

```
---
title: Title name
author: Joe Doe
cascade:
  author: Joe Doe
  show_author_byline: true
  show_comments: false
  show_post_date: true
  sidebar:
    show_sidebar_adunit: false
    text_link_label: View recent posts
    text_link_url: /blog_2/
description: 
layout: list-sidebar
show_author_byline: true
show_button_links: false
show_post_date: true
show_post_thumbnail: true
sidebar:
  title: Title name
  author:
  description: ""
  show_sidebar_adunit: true
  text_link_label: 
  text_link_url: /index.xml
thumbnail_left: true
---
```
