### ISSUE TITLE
Let projects go straight to external link

### ISSUE THREAD

**Issue by apreshill** [hugo-apero/hugo-apero#16]

**Comment by mccarthy-m-g** [comment]
This would be a great enhancement!

In the meantime, anyone trying to get this functionality on their site can use Netlify [redirects and rewrites](https://docs.netlify.com/routing/redirects/).

There are different options for how the redirect/rewrite works based on different needs. All you need to do is add what you want to redirect to the `netlify.toml` file in the root directory.

Here’s an example from the site I’m building. The `from` argument is the link of a post, the `to` argument is a bookdown book from another repository with its own site, the `status = 200` argument makes it so the redirect will rewrite the URL of the page I’m redirecting to in the users browser (the bookdown book will appear as a subdirectory of my domain with the root URL of the book starting at the URL of the `to` argument), and the `force` argument ensures that the bookdown book continues looking for content relative to its own root directory rather than my site’s root directory.

```toml
[[redirects]]
  from = "/self-study/an-introduction-to-statistical-learning/*"
  to = "https://tidytales-an-introduction-to-statistical-learning.netlify.app/:splat"
  status = 200
  force = true
```
