### ISSUE TITLE
How to show the table of content in the sidebar

### ISSUE THREAD

**Issue by xiaochi-liu** [hugo-apero/hugo-apero#49]
Hello. I'm learning `hugo-apero` to build my blog. I'd like each page within the blog section contains a sidebar and shows the table of content (i.e., "ON THIS PAGE"). However, it just didn't show up. May I ask how to handle this problem?

I have set the section configuration file (`/content/blog/_index.md`) as follows:

```
# set up common front matter for all pages inside blog/
cascade:
  layout: single-sidebar  # single or single-sidebar
  sidebar_left: false
  sidebar:
    text_contents_label: On this page
    show_sidebar_adunit: false
    # text_series_label: In this series
    text_link_label: ""
    text_link_url: ""
```

And I didn't set anything strange on the single page (`/content/blog/2021-09-07-writing-process-test/index.Rmarkdown`):

```
---
title: Writing Process Test
author: Xiaochi Liu
date: '2021-09-07'
slug: []
categories:
  - Scientific Writing
tags:
  - Scientific Writing
subtitle: ''
excerpt: ''
series: ~
---
```

However, there is no table of content in the sidebar:

![Screen Shot 2021-09-07 at 08 55 58](https://user-images.githubusercontent.com/48895627/132264424-8a8c84e6-b74a-4b9a-bf4b-1adb793df136.png)

Your kind guidance is much appreciated!
