### ISSUE TITLE
Add icon for YouTube

### ISSUE THREAD

**Issue by Lextuga007** [hugo-apero/hugo-apero#8]
I can see that the icons used in the pages come from font awesome but I'm not sure how to add something new like YouTube. I was particularly looking at adding it to the project links.

Thanks

**Comment by apreshill** [comment]
Hi! These are using font awesome icons, where you have to use the font awesome icon you want first, like:
https://fontawesome.com/icons?d=gallery&q=youtube&m=free

Then specify the right icon minus the `fa-` prefix (`youtube`) and the brand pack (here, `fab` for font awesome brands). Here is an example:



https://raw.githubusercontent.com/hugo-apero/hugo-apero/main/exampleSite/content/project/bakeoff/index.md

```
---
title: "Bakeoff"
subtitle: "An R Package"
excerpt: "This theme has a form-to-email feature built in, thanks to the simple Formspree integration. All you need to activate the form is a valid recipient email address saved in the form front matter."
date: 2019-07-01
author: "Eric Anderson"
draft: false
tags:
  - hugo-site
categories:
  - Theme Features
  - R
  - package
layout: single
links:
- icon: door-open
  icon_pack: fas
  name: website
  url: https://bakeoff.netlify.com/
- icon: github
  icon_pack: fab
  name: code
  url: https://github.com/apreshill/bakeoff
---
```

So for you, you'd want:

```
links:
- icon: youtube
  icon_pack: fab
  name: website
  url: https://bakeoff.netlify.com/
```

I'm realizing I documented it for the social icons, but not for talks or projects 🙈 
https://github.com/hugo-apero/hugo-apero/blob/2c923ad40eb462a607b7a7cbdbe22f3da3e1a710/exampleSite/config.toml#L79-L83

https://hugo-apero-docs.netlify.app/blog/social/

Does that help?
